# instead of Docker Run Container
services:
  master1:
    build:
      context: .
    hostname: Master1
    container_name: Master1
    ports:
      - "19988:9870"   # Namenode Web UI
      - "19989:8088"  # ResourceManager Web UI
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD-SHELL", "nc -zw 2 Master1 8020"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s    

  master2:
    build:
      context: .
    hostname: Master2
    container_name: Master2
    ports:
      - "19990:9870"   # Namenode Web UI
      - "19991:8088"  # ResourceManager Web UI
    networks:
      - hadoop-net 

  master3:
    build:
      context: .
    hostname: Master3
    container_name: Master3
    ports:
      - "19992:9870"   # Namenode Web UI
      - "19993:8088"  # ResourceManager Web UI
    networks:
      - hadoop-net 
      
  worker1:
    build:
      context: .
    hostname: Worker1
    container_name: Worker1
    networks:
      - hadoop-net  
    depends_on:
      master1:
        condition: service_healthy
      

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    ports:
      - "5562:5432"
    networks:
      - hadoop-net
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U hiveuser -d metastore"]  # Added -d metastore
     interval: 10s
     timeout: 5s
     retries: 5

  metastore:
    build:
      context: .
    hostname: Metastore
    container_name: Metastore
    ports:
      - "9983:9083"  # Hive Metastore Web UI
    networks:
      - hadoop-net 
    depends_on:
      postgres:
        condition: service_healthy
      master1:
        condition: service_healthy

  hive-server:
    build:
      context: .
    hostname: HiveServer2
    container_name: HiveServer2
    ports:
      - "10370:10000"  # HiveServer2 Web UI
    networks:
      - hadoop-net 
    depends_on:
      metastore:
        condition: service_started         

networks:
  hadoop-net:
    driver: bridge 
    name: hadoop-net   